export const driverConstants = {
    SET_PROFILE:'SET_PROFILE',
    EDIT_REAL_NAME:'EDIT_REAL_NAME',
    SET_DRIVING_LICENSE: 'SET_DRIVING_LICENSE',
    EDIT_VEHICLE:'EDIT_VEHICLE',
    SET_DRIVER: 'SET_DRIVER',
    SET_VENDOR: 'SET_VENDOR'
}
