export const driverConstants = {
    SET_PROFILE:'SET_PROFILE',
    SET_DRIVING_LICENSE: 'SET_DRIVING_LICENSE',
    SET_DRIVER: 'SET_DRIVER',
    SET_VENDOR: 'SET_VENDOR',
    SET_VEHICLE_INFO: 'SET_VEHICLE_INFO',
    SET_REAL_NAME_INFORMATION: 'SET_REAL_NAME_INFORMATION',
    SET_PROFILE_AVATAR: 'SET_PROFILE_AVATAR',
    SET_REAL_NAME_FRONT_IMAGE: 'SET_REAL_NAME_FRONT_IMAGE',
    SET_REAL_NAME_BACK_IMAGE: 'SET_REAL_NAME_BACK_IMAGE',
    SET_DRIVING_LICENSE_BACK_IMAGE: 'SET_DRIVING_LICENSE_BACK_IMAGE',
    SET_DRIVING_LICENSE_FRONT_IMAGE: 'SET_DRIVING_LICENSE_FRONT_IMAGE'
}
