export const driverConstants = {
    EDIT_PROFILE:'EDIT_PROFILE',
    EDIT_VENDOR:'EDIT_VENDOR',
    EDIT_REAL_NAME:'EDIT_REAL_NAME',
    EDIT_DRIVER_LICENSE: 'EDIT_DRIVER_LICENSE',
    EDIT_VEHICLE:'EDIT_VEHICLE'
} 